---
- name: Converge
  hosts: all
  connection: local
  vars:
    clamav_clamwatch: true
  tasks:
    - name: "Include ClamAV"
      ansible.builtin.include_role:
        name: "osx_provisioner.clamav"
