---
- name: Set CI Machine Type
  ansible.builtin.set_fact:
    ansible_machine: "{{ lookup('env', 'PLATFORM') }}"

- name: Load Default Var Content
  ansible.builtin.include_vars: "../../../defaults/main.yml"

- name: Capture Root Processes
  ansible.builtin.command: ps -u root
  register: root_processes
  changed_when: not root_processes.stdout

- name: Create Root Processes Match String
  ansible.builtin.set_fact:
    root_process_match_string1: '{{ brew_prefix }}/sbin/clamd --foreground -c {{ clamav_clamd_config_file }}'
    root_process_match_string2: '/bin/bash {{ brew_prefix }}/bin/clamwatch {{ clamav_clamwatch_target_folder }} {{ clamav_clamwatch_quarantine_folder }} {{ clamav_clamwatch_log_file }}'

- name: Capture _clamav Processes
  ansible.builtin.command: ps -u _clamav
  register: _clamav_processes
  changed_when: not _clamav_processes.stdout

- name: Create _clamav Processes Match String
  ansible.builtin.set_fact:
    _clamav_processes_match_string: '{{ brew_prefix }}/bin/freshclam --daemon --foreground --config-file {{ clamav_freshclam_config_file }}'
